export const BASELINE = {
  brent_prewar: 68, wti_prewar: 64, dubai_prewar: 65, urals_prewar: 42,
  brent_peak: 138, dubai_peak: 166,
  us_gas_prewar: 2.98, ca_gas_prewar: 4.20, us_diesel_prewar: 3.50,
  henry_hub_prewar: 2.80, jkm_prewar: 13.8, ttf_prewar: 11.6,
  urea_prewar: 320, dap_prewar: 520,
  wheat_prewar: 5.40, corn_prewar: 4.20, soybeans_prewar: 10.20,
  gold_prewar: 5226, silver_prewar: 84, copper_prewar: 4.10,
  sp500_prewar: 6879, nasdaq_prewar: 22668, dow_prewar: 48978, treasury_10y_prewar: 4.20,
  vlcc_day_rate_prewar: 35000, baltic_dry_prewar: 1450,
  btc_prewar: 65500, eth_prewar: 2500,
  hormuz_normal_oil_flow: 20, hormuz_normal_lng_flow: 5.2, global_oil_demand: 105.17,
  us_spr: 395.2, china_reserves_days: 108, japan_reserves_days: 147,
  south_korea_reserves_days: 178, india_reserves_days: 46, iea_release: 400,
  war_start_date: '2026-02-28', pentagon_budget_request: 200, daily_war_cost: 1.75,
  us_targets_struck: 8000, iran_navy_destroyed: 50, iran_launchers_destroyed_pct: 70,
  iran_displaced: 3200000, lebanon_displaced: 1000000,
};

export const CURRENT_METRICS: Record<string, { value: string; label: string; category: string; source: string }> = {
  'oil.brent.current': { value: '112', label: 'Brent Crude ($/bbl)', category: 'energy', source: 'Bloomberg' },
  'oil.wti.current': { value: '98', label: 'WTI Crude ($/bbl)', category: 'energy', source: 'Bloomberg' },
  'oil.dubai.current': { value: '135', label: 'Dubai Crude ($/bbl)', category: 'energy', source: 'Bloomberg' },
  'oil.urals.current': { value: '72', label: 'Urals Crude ($/bbl)', category: 'energy', source: 'Reuters' },
  'gas.us.national': { value: '3.88', label: 'US Gas National Avg ($/gal)', category: 'energy', source: 'AAA' },
  'gas.us.california': { value: '5.34', label: 'California Gas ($/gal)', category: 'energy', source: 'AAA' },
  'gas.us.diesel': { value: '5.19', label: 'US Diesel ($/gal)', category: 'energy', source: 'AAA' },
  'hormuz.oil.flow': { value: '0.6', label: 'Hormuz Oil Flow (M bbl/d)', category: 'energy', source: 'Kpler/est' },
  'hormuz.lng.flow': { value: '0.3', label: 'Hormuz LNG Flow (Bcf/d)', category: 'energy', source: 'Kpler/est' },
  'hormuz.tankers.stranded': { value: '150', label: 'Tankers Stranded', category: 'energy', source: 'MarineTraffic' },
  'hormuz.insurance': { value: 'WITHDRAWN', label: 'War-Risk Insurance', category: 'energy', source: 'Lloyds' },
  'hormuz.transit.cost': { value: '2000000', label: 'Per-Transit Cost ($)', category: 'energy', source: 'Reuters' },
  'urea.current': { value: '620', label: 'Urea ($/ton)', category: 'energy', source: 'CBOT' },
  'qatar.lng.damage.pct': { value: '17', label: 'Qatar LNG Capacity Lost (%)', category: 'energy', source: 'QatarEnergy' },
  'qatar.lng.repair.years': { value: '5', label: 'Qatar Repair Timeline (yrs)', category: 'energy', source: 'Reuters' },
  'market.sp500.current': { value: '6506', label: 'S&P 500', category: 'financial', source: 'Yahoo Finance' },
  'market.nasdaq.current': { value: '21648', label: 'Nasdaq', category: 'financial', source: 'Yahoo Finance' },
  'market.dow.current': { value: '45577', label: 'Dow Jones', category: 'financial', source: 'Yahoo Finance' },
  'market.treasury10y': { value: '4.39', label: '10Y Treasury (%)', category: 'financial', source: 'FRED' },
  'market.dxy': { value: '99.5', label: 'US Dollar Index', category: 'financial', source: 'ICE' },
  'market.gold': { value: '4494', label: 'Gold ($/oz)', category: 'financial', source: 'COMEX' },
  'war.day': { value: '22', label: 'Day of War', category: 'military', source: 'Calculated' },
  'war.targets.struck': { value: '8000', label: 'US Targets Struck', category: 'military', source: 'CENTCOM' },
  'war.iran.navy.destroyed': { value: '50', label: 'Iran Navy Vessels Sunk', category: 'military', source: 'CENTCOM' },
  'war.iran.launchers.pct': { value: '70', label: 'Missile Launchers Destroyed (%)', category: 'military', source: 'Pentagon' },
  'war.basij.killed': { value: '4500', label: 'Basij/IRGC Killed (IDF est)', category: 'military', source: 'IDF' },
  'war.us.kia': { value: '13', label: 'US Military KIA', category: 'military', source: 'CENTCOM' },
  'war.us.wounded': { value: '140', label: 'US Military Wounded', category: 'military', source: 'CENTCOM' },
  'war.mojtaba.status': { value: 'UNKNOWN - No public appearance, written statements only', label: 'Mojtaba Khamenei Status', category: 'political', source: 'Multiple' },
  'war.ultimatum': { value: '48hr power plant threat - Mar 21 6:44PM', label: 'Active Ultimatum', category: 'political', source: 'Truth Social' },
  'iran.dead.hrana': { value: '3220', label: 'Iran Deaths (HRANA)', category: 'humanitarian', source: 'HRANA' },
  'iran.dead.hengaw': { value: '5900', label: 'Iran Deaths (Hengaw)', category: 'humanitarian', source: 'Hengaw' },
  'iran.dead.govt': { value: '1500', label: 'Iran Deaths (Govt)', category: 'humanitarian', source: 'Iran Health Min' },
  'iran.dead.aljazeera': { value: '1444', label: 'Iran Deaths (AJ Tracker)', category: 'humanitarian', source: 'Al Jazeera' },
  'iran.dead.civilian': { value: '1398', label: 'Iran Civilian Dead (HRANA)', category: 'humanitarian', source: 'HRANA' },
  'iran.dead.children': { value: '210', label: 'Iran Children Dead', category: 'humanitarian', source: 'HRANA' },
  'iran.wounded': { value: '12000', label: 'Iran Wounded', category: 'humanitarian', source: 'Red Crescent' },
  'iran.displaced': { value: '3200000', label: 'Iran Displaced', category: 'humanitarian', source: 'UNHCR' },
  'iran.schools.damaged': { value: '66', label: 'Schools Damaged', category: 'humanitarian', source: 'Iran Edu Min' },
  'iran.internet.pct': { value: '1', label: 'Iran Internet (%)', category: 'humanitarian', source: 'NetBlocks' },
  'iran.arrests.wartime': { value: '195', label: 'Wartime Arrests', category: 'humanitarian', source: 'HRANA' },
  'iran.executions': { value: '3', label: 'Protest Executions', category: 'humanitarian', source: 'HRANA' },
  'israel.dead': { value: '18', label: 'Israel Dead', category: 'humanitarian', source: 'MDA' },
  'israel.wounded': { value: '3730', label: 'Israel Wounded', category: 'humanitarian', source: 'MDA' },
  'iraq.dead': { value: '61', label: 'Iraq Dead', category: 'humanitarian', source: 'Iraqi Health Auth' },
  'uae.dead': { value: '8', label: 'UAE Dead', category: 'humanitarian', source: 'UAE MoD' },
  'kuwait.dead': { value: '5', label: 'Kuwait Dead', category: 'humanitarian', source: 'Kuwait MoD' },
  'lebanon.dead': { value: '1000', label: 'Lebanon Dead', category: 'humanitarian', source: 'Lebanese authorities' },
  'lebanon.displaced': { value: '1000000', label: 'Lebanon Displaced', category: 'humanitarian', source: 'UNHCR' },
  'pakistan.dead': { value: '30', label: 'Pakistan Dead (protests)', category: 'humanitarian', source: 'Reuters' },
  'gcc.qatar.damage': { value: '42', label: 'Qatar Damage ($B)', category: 'economic', source: 'Estimated' },
  'gcc.uae.damage': { value: '18', label: 'UAE Damage ($B)', category: 'economic', source: 'Estimated' },
  'gcc.kuwait.damage': { value: '15', label: 'Kuwait Damage ($B)', category: 'economic', source: 'Estimated' },
  'gcc.saudi.damage': { value: '8', label: 'Saudi Damage ($B)', category: 'economic', source: 'Estimated' },
  'gcc.bahrain.damage': { value: '5', label: 'Bahrain Damage ($B)', category: 'economic', source: 'Estimated' },
  'geo.diego.garcia': { value: 'Iran fired 2 IRBMs at 4000km — demonstrating undeclared range. 1 intercepted, 1 failed.', label: 'Diego Garcia Strike', category: 'geopolitical', source: 'WSJ/CNN' },
  'geo.ceasefire.iran': { value: '3 conditions: no future attacks, reparations, sovereign rights recognition', label: 'Iran Ceasefire Terms', category: 'geopolitical', source: 'Bloomberg/AJ' },
  'geo.ceasefire.us': { value: 'No ceasefire discussed (Trump Mar 21)', label: 'US Position', category: 'geopolitical', source: 'Truth Social' },
  'geo.ceasefire.israel': { value: 'Series of eliminations will not stop — 3+ more weeks planned', label: 'Israel Position', category: 'geopolitical', source: 'IDF' },
  'geo.nuclear.uranium': { value: '440kg of 60% enriched — LOCATION UNKNOWN', label: 'Missing HEU', category: 'geopolitical', source: 'IAEA/CSIS' },
  'geo.nuclear.fordow': { value: 'INOPERABLE since June 2025 (12 MOPs)', label: 'Fordow Status', category: 'geopolitical', source: 'ISIS/IAEA' },
  'geo.russia.benefit': { value: 'Urals at $72 (+38%), +$12B/2wk, US sanctions lifted, sat intel to Iran', label: 'Russia Gains', category: 'geopolitical', source: 'Axios/CBS' },
  'geo.china.reserves': { value: '108 days (1.2B bbl), ships transiting with Iranian permission', label: 'China Position', category: 'geopolitical', source: 'CNBC/Atlantic Council' },
  'regime.basij.killed': { value: '4500', label: 'Basij/Security Forces Killed', category: 'regime', source: 'IDF est Day 14' },
  'regime.basij.300': { value: '300 commanders killed in single Mar 17 overnight wave', label: 'Basij Mass Strike', category: 'regime', source: 'Iran International' },
  'regime.crowdsource': { value: 'Iranians sending checkpoint locations to IDF Farsi social media accounts', label: 'Crowdsourced Targeting', category: 'regime', source: 'WSJ/Reuters/AP' },
  'regime.checkpoints': { value: 'Basij setting up under bridges to hide from drones — degraded morale', label: 'Basij Morale', category: 'regime', source: 'Newsweek/AP' },
  'regime.pezeshkian': { value: 'Reports: no authority, cut off from leadership structures', label: 'President Status', category: 'regime', source: 'Arabic media/HotAir' },
};

export const COUNTRIES_DATA = [
  { code: 'CN', name: 'China', flag: '🇨🇳', vulnerability: 82, oil_dependency_pct: 76, lng_dependency_pct: 15, reserve_days: 108, gdp_impact_pct: -1.2, inflation_impact_pct: 2.8, currency_change_pct: -3.1, stock_market_change_pct: -11, food_price_impact_pct: 8, policy_response: 'SPR release, rationing prep, pipeline acceleration from Russia', key_events: 'Chinese tankers transiting Hormuz with Iranian permission; emergency oil imports from Russia via ESPO pipeline' },
  { code: 'IN', name: 'India', flag: '🇮🇳', vulnerability: 91, oil_dependency_pct: 85, lng_dependency_pct: 52, reserve_days: 46, gdp_impact_pct: -2.1, inflation_impact_pct: 5.4, currency_change_pct: -5.8, stock_market_change_pct: -15, food_price_impact_pct: 14, policy_response: 'Emergency fuel rationing, subsidies, diplomatic neutrality, Russian oil pivot', key_events: 'INR hit record low; fuel rationing in 5 states; diplomatic efforts with both sides' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', vulnerability: 78, oil_dependency_pct: 88, lng_dependency_pct: 22, reserve_days: 147, gdp_impact_pct: -1.5, inflation_impact_pct: 3.2, currency_change_pct: -2.4, stock_market_change_pct: -9, food_price_impact_pct: 6, policy_response: 'IEA coordinated SPR release, nuclear restart acceleration', key_events: 'Restarted 3 additional nuclear reactors; coordinated SPR release with IEA' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', vulnerability: 80, oil_dependency_pct: 75, lng_dependency_pct: 35, reserve_days: 178, gdp_impact_pct: -1.3, inflation_impact_pct: 3.5, currency_change_pct: -4.1, stock_market_change_pct: -12, food_price_impact_pct: 7, policy_response: 'SPR release, emergency LNG contracts with Australia/US', key_events: 'Samsung/Hyundai warned of production cuts; Won at 3-year low' },
  { code: 'US', name: 'United States', flag: '🇺🇸', vulnerability: 35, oil_dependency_pct: 5, lng_dependency_pct: 0, reserve_days: 395, gdp_impact_pct: -0.4, inflation_impact_pct: 1.8, currency_change_pct: 1.2, stock_market_change_pct: -5.4, food_price_impact_pct: 4, policy_response: 'SPR release (400M bbl authorized), Iran sanctions unsanctioned, military ops $1.75B/day', key_events: 'SPR release; gas prices up $0.88/gal; Pentagon $200B supplemental request; Dow down 3,400pts' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', vulnerability: 55, oil_dependency_pct: 30, lng_dependency_pct: 18, reserve_days: 90, gdp_impact_pct: -0.8, inflation_impact_pct: 2.5, currency_change_pct: -1.2, stock_market_change_pct: -8, food_price_impact_pct: 5, policy_response: 'EU coordinated response, accelerated renewable push', key_events: 'DAX fell 8%; chemical industry warning of production cuts' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', vulnerability: 42, oil_dependency_pct: 15, lng_dependency_pct: 12, reserve_days: 60, gdp_impact_pct: -0.5, inflation_impact_pct: 2.1, currency_change_pct: -1.8, stock_market_change_pct: -6, food_price_impact_pct: 4, policy_response: 'North Sea production increase, coordinated sanctions', key_events: 'FTSE 100 down 6%; military support to US operations' },
  { code: 'FR', name: 'France', flag: '🇫🇷', vulnerability: 38, oil_dependency_pct: 20, lng_dependency_pct: 10, reserve_days: 90, gdp_impact_pct: -0.4, inflation_impact_pct: 1.9, currency_change_pct: -1.2, stock_market_change_pct: -7, food_price_impact_pct: 4, policy_response: 'Nuclear dominance shields electricity; diplomatic mediation attempts', key_events: 'CAC 40 down 7%; Macron leading ceasefire diplomatic effort' },
  { code: 'AE', name: 'UAE', flag: '🇦🇪', vulnerability: 72, oil_dependency_pct: 0, lng_dependency_pct: 0, reserve_days: 999, gdp_impact_pct: -3.5, inflation_impact_pct: 4.2, currency_change_pct: 0, stock_market_change_pct: -18, food_price_impact_pct: 12, policy_response: 'Emergency infrastructure repair, diversified export routes via Fujairah', key_events: 'Abu Dhabi/Dubai airports hit by Iranian missiles; $18B infrastructure damage; 8 dead' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', vulnerability: 48, oil_dependency_pct: 0, lng_dependency_pct: 0, reserve_days: 999, gdp_impact_pct: 2.5, inflation_impact_pct: 1.5, currency_change_pct: 0, stock_market_change_pct: -4, food_price_impact_pct: 6, policy_response: 'Increased production via East-West pipeline, profiting from price spike', key_events: 'Aramco pumping extra 1.5M bbl/day; minor Houthi-linked attacks; $8B damage from Iranian strikes' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', vulnerability: 95, oil_dependency_pct: 0, lng_dependency_pct: 0, reserve_days: 999, gdp_impact_pct: -8.5, inflation_impact_pct: 7.2, currency_change_pct: -0.5, stock_market_change_pct: -25, food_price_impact_pct: 15, policy_response: 'Emergency infrastructure repair, $42B damage assessment, 5-year LNG rebuild', key_events: 'Ras Laffan LNG facility 17% capacity loss from Iranian strikes; global LNG supply shock' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', vulnerability: 68, oil_dependency_pct: 0, lng_dependency_pct: 0, reserve_days: 999, gdp_impact_pct: -2.8, inflation_impact_pct: 3.8, currency_change_pct: -1.0, stock_market_change_pct: -14, food_price_impact_pct: 10, policy_response: 'Port reconstruction, alternative export via Saudi pipeline', key_events: '5 dead from missile strikes; $15B port/refinery damage; oil exports rerouted' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', vulnerability: 75, oil_dependency_pct: 0, lng_dependency_pct: 0, reserve_days: 999, gdp_impact_pct: -4.2, inflation_impact_pct: 5.5, currency_change_pct: 0, stock_market_change_pct: -20, food_price_impact_pct: 13, policy_response: 'US 5th Fleet base hit; $5B damage; sectarian tensions rising', key_events: 'Naval base targeted; Shia protests; financial sector disrupted' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', vulnerability: 99, oil_dependency_pct: 0, lng_dependency_pct: 0, reserve_days: 0, gdp_impact_pct: -35, inflation_impact_pct: 120, currency_change_pct: -80, stock_market_change_pct: -60, food_price_impact_pct: 200, policy_response: 'Total war footing; communications blackout; Basij mobilization', key_events: '8000+ targets struck; navy destroyed; 3220-5900 dead; 3.2M displaced; 1% internet' },
  { code: 'RU', name: 'Russia', flag: '🇷🇺', vulnerability: 15, oil_dependency_pct: 0, lng_dependency_pct: 0, reserve_days: 999, gdp_impact_pct: 2.2, inflation_impact_pct: -0.5, currency_change_pct: 4.8, stock_market_change_pct: 10, food_price_impact_pct: 2, policy_response: 'Profiting massively — Urals above benchmark, sanctions lifted, intel to Iran', key_events: 'Urals at $72 (38% above pre-war $52); US sanctions lifted; satellite intel to Iran; +$12B/2wk revenue' },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', vulnerability: 65, oil_dependency_pct: 40, lng_dependency_pct: 30, reserve_days: 30, gdp_impact_pct: -1.8, inflation_impact_pct: 8.5, currency_change_pct: -7.2, stock_market_change_pct: -13, food_price_impact_pct: 16, policy_response: 'Balancing NATO obligations with Iran trade; Iraqi pipeline alternative', key_events: 'Lira crashed to record low; refugee inflow from Iraq; energy crisis deepening' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', vulnerability: 88, oil_dependency_pct: 60, lng_dependency_pct: 45, reserve_days: 20, gdp_impact_pct: -3.5, inflation_impact_pct: 12, currency_change_pct: -8.5, stock_market_change_pct: -18, food_price_impact_pct: 22, policy_response: 'IMF emergency request; fuel rationing; load shedding 12+ hrs/day', key_events: '30 dead in protests; rolling blackouts; PKR collapsed; food riots in Karachi' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', vulnerability: 85, oil_dependency_pct: 55, lng_dependency_pct: 40, reserve_days: 15, gdp_impact_pct: -2.8, inflation_impact_pct: 10, currency_change_pct: -6.5, stock_market_change_pct: -16, food_price_impact_pct: 20, policy_response: 'Emergency fuel imports from India; garment industry shutdowns', key_events: 'RMG factories shutting due to power cuts; forex reserves critical' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱', vulnerability: 60, oil_dependency_pct: 10, lng_dependency_pct: 5, reserve_days: 90, gdp_impact_pct: -1.5, inflation_impact_pct: 3.0, currency_change_pct: -4.5, stock_market_change_pct: -10, food_price_impact_pct: 5, policy_response: 'Active military operations; Hezbollah front; Iron Dome surge', key_events: '18 dead, 3730 wounded from missile attacks; IDF conducting parallel ops in Lebanon' },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶', vulnerability: 70, oil_dependency_pct: 0, lng_dependency_pct: 0, reserve_days: 999, gdp_impact_pct: 1.0, inflation_impact_pct: 6.0, currency_change_pct: -2.0, stock_market_change_pct: -8, food_price_impact_pct: 12, policy_response: 'Caught between US/Iran; PMF bases struck; oil revenue up but instability rising', key_events: '61 dead from strikes on PMF positions; Kurdish pipeline exports surging' },
];

export const TRADE_ROUTES = [
  { id: 'hormuz-china', route_name: 'Hormuz → China (VLCC)', pre_war_flow: 8.5, current_flow: 0.3, unit: 'M bbl/day', status: 'Near-Blocked', notes: 'Only Chinese-flagged vessels with Iranian permission transiting' },
  { id: 'hormuz-india', route_name: 'Hormuz → India', pre_war_flow: 4.2, current_flow: 0.1, unit: 'M bbl/day', status: 'Blocked', notes: 'India not willing to risk tankers; rerouting via Russia' },
  { id: 'hormuz-japan', route_name: 'Hormuz → Japan', pre_war_flow: 3.1, current_flow: 0, unit: 'M bbl/day', status: 'Blocked', notes: 'Complete halt; SPR drawdown active' },
  { id: 'hormuz-korea', route_name: 'Hormuz → South Korea', pre_war_flow: 2.8, current_flow: 0, unit: 'M bbl/day', status: 'Blocked', notes: 'Zero flow; emergency LNG from Australia' },
  { id: 'hormuz-europe', route_name: 'Hormuz → Europe', pre_war_flow: 1.4, current_flow: 0, unit: 'M bbl/day', status: 'Blocked', notes: 'European tankers redirected; North Sea/Norway supply up' },
  { id: 'qatar-lng', route_name: 'Qatar LNG (via Hormuz)', pre_war_flow: 5.2, current_flow: 0.3, unit: 'Bcf/day', status: 'Near-Blocked', notes: 'Ras Laffan 17% capacity damaged; remaining output trapped' },
  { id: 'habshan-fujairah', route_name: 'UAE Habshan-Fujairah Pipeline', pre_war_flow: 1.5, current_flow: 1.8, unit: 'M bbl/day', status: 'Active - Maxed', notes: 'Bypasses Hormuz; running above capacity' },
  { id: 'saudi-east-west', route_name: 'Saudi East-West Pipeline', pre_war_flow: 2.0, current_flow: 5.0, unit: 'M bbl/day', status: 'Active - Surge', notes: 'Petroline to Red Sea; Saudi adding 1.5M bbl/day extra' },
  { id: 'iraq-turkey', route_name: 'Iraq-Turkey (Kirkuk-Ceyhan)', pre_war_flow: 0.45, current_flow: 0.9, unit: 'M bbl/day', status: 'Active - Doubled', notes: 'Kurdish pipeline at max capacity; Turkey benefiting from transit fees' },
  { id: 'russia-china-espo', route_name: 'Russia → China (ESPO Pipeline)', pre_war_flow: 1.6, current_flow: 2.1, unit: 'M bbl/day', status: 'Active - Surge', notes: 'Emergency ramp; China paying premium for guaranteed flow' },
  { id: 'russia-china-pipe', route_name: 'Russia → China (Power of Siberia)', pre_war_flow: 38, current_flow: 42, unit: 'Bcm/year', status: 'Active - Increased', notes: 'Gas flow accelerated; POS-2 talks expedited' },
  { id: 'russia-india-sea', route_name: 'Russia → India (Sea Route)', pre_war_flow: 1.8, current_flow: 2.5, unit: 'M bbl/day', status: 'Active - Surge', notes: 'Urals crude at discount; Indian refiners maximizing purchases' },
  { id: 'us-lng-europe', route_name: 'US LNG → Europe', pre_war_flow: 12, current_flow: 14, unit: 'Bcf/day', status: 'Active - Max', notes: 'US LNG terminals at full capacity; spot prices 3x pre-war' },
  { id: 'us-lng-asia', route_name: 'US LNG → Asia', pre_war_flow: 4, current_flow: 5.5, unit: 'Bcf/day', status: 'Active - Surge', notes: 'Diverting from Europe to Asia due to premium prices' },
  { id: 'africa-oil', route_name: 'West Africa → Global', pre_war_flow: 4.2, current_flow: 5.0, unit: 'M bbl/day', status: 'Active - Up', notes: 'Nigeria, Angola ramping up; premium over Brent narrowing' },
  { id: 'latam-oil', route_name: 'Latin America → US/Asia', pre_war_flow: 3.8, current_flow: 4.5, unit: 'M bbl/day', status: 'Active - Up', notes: 'Brazil, Guyana, Venezuela (unsanctioned) exports surging' },
];

export const COMMODITIES_DATA = [
  { symbol: 'BRENT', name: 'Brent Crude', prewar: 68, current: 112, unit: '$/bbl', category: 'oil' },
  { symbol: 'WTI', name: 'WTI Crude', prewar: 64, current: 98, unit: '$/bbl', category: 'oil' },
  { symbol: 'DUBAI', name: 'Dubai Crude', prewar: 69, current: 135, unit: '$/bbl', category: 'oil' },
  { symbol: 'URALS', name: 'Urals Crude', prewar: 52, current: 72, unit: '$/bbl', category: 'oil' },
  { symbol: 'HENRY_HUB', name: 'Henry Hub Nat Gas', prewar: 3.45, current: 5.20, unit: '$/MMBtu', category: 'gas' },
  { symbol: 'JKM', name: 'JKM LNG (Asia)', prewar: 13.8, current: 38, unit: '$/MMBtu', category: 'gas' },
  { symbol: 'TTF', name: 'TTF Nat Gas (Europe)', prewar: 11.6, current: 32, unit: '$/MMBtu', category: 'gas' },
  { symbol: 'UREA', name: 'Urea', prewar: 320, current: 620, unit: '$/ton', category: 'fertilizer' },
  { symbol: 'DAP', name: 'DAP', prewar: 530, current: 760, unit: '$/ton', category: 'fertilizer' },
  { symbol: 'WHEAT', name: 'Wheat', prewar: 5.40, current: 6.20, unit: '$/bushel', category: 'food' },
  { symbol: 'CORN', name: 'Corn', prewar: 4.20, current: 5.10, unit: '$/bushel', category: 'food' },
  { symbol: 'SOYBEANS', name: 'Soybeans', prewar: 10.20, current: 12.40, unit: '$/bushel', category: 'food' },
  { symbol: 'GOLD', name: 'Gold', prewar: 5226, current: 4494, unit: '$/oz', category: 'metals' },
  { symbol: 'SILVER', name: 'Silver', prewar: 84, current: 70, unit: '$/oz', category: 'metals' },
  { symbol: 'COPPER', name: 'Copper', prewar: 4.10, current: 4.85, unit: '$/lb', category: 'metals' },
  { symbol: 'BTC', name: 'Bitcoin', prewar: 65500, current: 68951, unit: '$', category: 'crypto' },
  { symbol: 'ETH', name: 'Ethereum', prewar: 2400, current: 2082, unit: '$', category: 'crypto' },
  { symbol: 'VLCC', name: 'VLCC Day Rate', prewar: 38000, current: 105000, unit: '$/day', category: 'shipping' },
  { symbol: 'BDI', name: 'Baltic Dry Index', prewar: 1480, current: 2200, unit: 'index', category: 'shipping' },
];

export const TIMELINE_EVENTS = [
  { date: '2026-02-28', event: 'Operation Epic Fury begins — US strikes 150+ targets across Iran', category: 'military', impact_score: 10, source: 'CENTCOM' },
  { date: '2026-02-28', event: 'Iran retaliates — missiles hit UAE, Kuwait, Bahrain, Israel', category: 'military', impact_score: 9, source: 'Multiple' },
  { date: '2026-02-28', event: 'Strait of Hormuz effectively closed — insurance withdrawn', category: 'economic', impact_score: 10, source: 'Lloyds' },
  { date: '2026-03-01', event: 'Brent spikes to $138/bbl; Dubai crude at $166', category: 'economic', impact_score: 9, source: 'Bloomberg' },
  { date: '2026-03-02', event: 'IEA announces coordinated 400M barrel SPR release', category: 'economic', impact_score: 7, source: 'IEA' },
  { date: '2026-03-03', event: 'Iran cuts internet to 1% — near total blackout', category: 'humanitarian', impact_score: 8, source: 'NetBlocks' },
  { date: '2026-03-05', event: 'Iran fires 2 IRBMs at Diego Garcia — 4000km range surprise', category: 'military', impact_score: 9, source: 'WSJ/CNN' },
  { date: '2026-03-07', event: 'Qatar Ras Laffan LNG facility hit — 17% capacity destroyed', category: 'economic', impact_score: 9, source: 'QatarEnergy' },
  { date: '2026-03-10', event: 'US unsanctions Iranian oil to lower prices — contradicts bombing campaign', category: 'economic', impact_score: 7, source: 'Reuters' },
  { date: '2026-03-14', event: 'IDF begins parallel operations in Lebanon', category: 'military', impact_score: 8, source: 'IDF' },
  { date: '2026-03-17', event: '300 Basij commanders killed in single overnight wave', category: 'military', impact_score: 8, source: 'Iran International' },
  { date: '2026-03-17', event: 'Iranians crowdsourcing checkpoint locations to IDF', category: 'regime', impact_score: 7, source: 'WSJ/Reuters/AP' },
  { date: '2026-03-19', event: 'Brent settles to $107-114 range — SPR releases taking effect', category: 'economic', impact_score: 6, source: 'Bloomberg' },
  { date: '2026-03-20', event: 'Russia sanctions fully lifted by US — quid pro quo suspected', category: 'geopolitical', impact_score: 8, source: 'Axios/CBS' },
  { date: '2026-03-21', event: 'Trump ultimatum: 48hr threat to strike power plants', category: 'political', impact_score: 9, source: 'Truth Social' },
  { date: '2026-03-21', event: 'Iran offers ceasefire — 3 conditions', category: 'diplomatic', impact_score: 8, source: 'Bloomberg/AJ' },
  { date: '2026-03-22', event: 'War Day 22 — HRANA: 3220 dead; Hengaw: 5900 dead', category: 'humanitarian', impact_score: 9, source: 'HRANA/Hengaw' },
];
